### ISSUE TITLE
Log4j2: Empty jar created for log4j2

### ISSUE THREAD

**Issue by raipc** [axibase/aggregation-log-filter#48]
Since version 2.0.4 log4j2 adapter without classes is published
https://search.maven.org/artifact/com.axibase/aggregation-log-filter-log4j2/2.0.6/jar

Normal jar should have size of 20 kb.

We need log4j2 for moex-consumer CI releases

**Comment by raipc** [comment]
I could reproduce the issue locally with java 7. Java 8 creates jar normally.
@rodionos I think time has come to drop Java 7 support

**Comment by rodionos** [comment]
Concur, Java 8 is the minimum level for us to support in all repos.
